# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('created_at', models.DateField(default=datetime.datetime(2017, 10, 10, 13, 47, 32, 887822, tzinfo=utc))),
            ],
        ),
    ]
