# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 10, 13, 48, 25, 351489, tzinfo=utc)),
        ),
    ]
