# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20171010_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 10, 10, 13, 55, 10, 473168, tzinfo=utc)),
        ),
    ]
