# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20171010_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=254),
        ),
    ]
