# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20171012_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
