# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20171013_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
