# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
