# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2017, 10, 10, 23, 1, 47, 933435, tzinfo=utc))),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Member')),
            ],
        ),
    ]
