# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20171010_1358'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime(2017, 10, 10, 23, 8, 23, 366731, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
