# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20171010_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2017, 10, 10, 23, 16, 38, 903460, tzinfo=utc)),
        ),
    ]
