# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20171012_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
            preserve_default=False,
        ),
    ]
